# Generated by Django 4.0.4 on 2022-05-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
